export const LOAD_DEST_SUCCESS = 'LOAD_DESTINATION_SUCCESS';
export const CREATE_DEST_SUCCESS = 'CREATE_DESTINATION_SUCCESS';
export const UPDATE_DEST_SUCCESS = 'UPDATE_DESTINATION_SUCCESS';
export const LOAD_ALL_DESTS_SUCCESS = 'LOAD_ALL_DESTINATIONS_SUCCESS';
export const DELETE_DEST_SUCCESS = 'DELETE_DESTINATION_SUCCESS';
export const LOAD_RECENT_ACTIVITIES_SUCCESS = 'LOAD_RECENT_ACTIVITIES_SUCCESS';
